// <auto-generated />
namespace NZ.Anbar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removekindfrosh : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removekindfrosh));
        
        string IMigrationMetadata.Id
        {
            get { return "202510190751180_remove-kind-frosh"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
