// <auto-generated />
namespace NZ.General.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtest : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtest));
        
        string IMigrationMetadata.Id
        {
            get { return "202203161421490_add-test"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
