// <auto-generated />
namespace NZ.General.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class adduserlockEmpty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(adduserlockEmpty));
        
        string IMigrationMetadata.Id
        {
            get { return "202506300549278_add-user-lock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
