// <auto-generated />
namespace Nz.Bar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addersalkarkhane : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addersalkarkhane));
        
        string IMigrationMetadata.Id
        {
            get { return "202508031451109_add-ersal-karkhane"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
