// <auto-generated />
namespace Nz.Bar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changecolumntypedecimal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changecolumntypedecimal));
        
        string IMigrationMetadata.Id
        {
            get { return "202507230655356_change-column-type-decimal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
