// <auto-generated />
namespace NZ.Anbar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changesubgroup : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changesubgroup));
        
        string IMigrationMetadata.Id
        {
            get { return "202509270817377_change-sub-group"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
