// <auto-generated />
namespace NZ.Anbar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class modifysaleskind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(modifysaleskind));
        
        string IMigrationMetadata.Id
        {
            get { return "202502081523449_modify-sales-kind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
