// <auto-generated />
namespace NZ.Anbar.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class changewebsitekind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(changewebsitekind));
        
        string IMigrationMetadata.Id
        {
            get { return "202510091348300_change-website-kind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
