// <auto-generated />
namespace Nz.Aqsat.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removecodefromaqsatkind : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removecodefromaqsatkind));
        
        string IMigrationMetadata.Id
        {
            get { return "202511281619385_remove-code-from-aqsat-kind"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
