// <auto-generated />
namespace NZ.Xazane.DataLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addshenasesayadi : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addshenasesayadi));
        
        string IMigrationMetadata.Id
        {
            get { return "202510201630058_add-shenase-sayadi"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
